### ISSUE TITLE
clojurescript , figwheel version mismatch

### ISSUE THREAD

**Issue by zerg000000** [duct-framework/server.figwheel#2]
`figwheel-sidecar 0.5.8` depends on `goog.net.jsloader.load`
which is removed since `Closure Library v20170806`.
However, `clojurescript 1.9.908` is depends on Closure Library `0.0-20170809-b9c14c6b` and this will cause throwing `goog.net.jsloader.load` not found when `reset` in duct repl.

Please consider upgrade figwheel to `0.5.13`, according to [Change Log](https://github.com/bhauman/lein-figwheel/blob/master/CHANGES.md) the use of `goog.net.jsloader.load` is removed.

**Comment by weavejester** [comment]
Upgrading to 0.5.13 is on my todo list, but because server.figwheel reaches into the internal API of Figwheel, it's always a huge pain to upgrade.

**Comment by zerg000000** [comment]
I had added the `figwheel-sidecar 0.5.13` explicitly, seems not much problems.

**Comment by weavejester** [comment]
Are you using it from a blank target directory? I'm finding updating the dependency to 0.5.13 results in the server not compiling new files.

**Comment by weavejester** [comment]
Fixed. Turned out to be an error in the integration code. The internal API calls that server.figwheel uses haven't changed from 0.5.8 to 0.5.13, so this upgrade was relatively straightforward.
